title: Harjaap Bhatia
description: An aspiring Data scientist !
darkmode: true
buttons:
  zip_url: https://github.com/harjaap7b
  zip_title: View GitHub Profile
  zip_hide: false
theme: jekyll-theme-cayman
